### PR TITLE
add Sphinx docs framework

### PR DESCRIPTION
**Pull request by mperrin**
This PR adds a `docs` subdirectory for Sphinx, along with necessary config files. The subdir contains a couple mostly-blank files to be filled in, eventually, with examples in both RestructuredText and Jupyter notebook format.  

Once this is installed, you can do `make html` from in the docs directory, or `python setup.py build_docs` in the main directory. (These are equivalent, just two different options depending on where you are).

### CODE REVIEW

**Comment by mperrin** [comment]
Oh, I should also add a docs build to the Travis config.

**Comment by bhilbert4** [comment]
@mperrin is there more you were going to add to this? I just want to make sure that you're not waiting on me to merge this PR.

**Comment by mperrin** [comment]
actually yeah, I was sort of waiting for you or someone else to look at, comment, or approve. I generally don't like merging in PRs without at least some cursory version of code review!

**Comment by mperrin** [comment]
But now that you remind me, I should go ahead and add a docs build to Travis like I mentioned above. One moment...

**Comment by bhilbert4** [comment]
I read through all the files you added, but with my limited Sphinx knowledge, I don't think I can provide a very useful review. If you want someone with more experience to look at your files, you may have to wait for @Johannes-Sahlmann, who is leaving on vacation. Unless @laurenmarietta is familiar with Sphinx?

**Comment by mperrin** [comment]
I don't think it needs particular review in detail since most of this is boilerplate copied from elsewhere. It was more a matter of someone giving a thumbs up overall. 

One particular question is where to host the documentation. Internally or publicly available?  ReadTheDocs is a good option for publicly available code. There is already some other project that grabbed the url `mirage.readthedocs.io` so this would have to settle for something like `jwst-mirage.readthedocs.io` but presumably that's OK.

**Comment by bhilbert4** [comment]
I think ReadTheDocs makes sense. At some point this will be a public tool, so we'll need public facing documentation. Bummer that `mirage.readthedocs.io` is already taken. `jwst-mirage.readthedocs.io` is a good alternative though.

**Comment by bhilbert4** [comment]
Looks like Travis failed because `sphinx` is not installed.

**Comment by mperrin** [comment]
> Looks like Travis failed because sphinx is not installed.

OK, I'm on it. Must have missed something in the setup files.

**Comment by bhilbert4** [comment]
Hmm. What do you make of the timeout error in this Travis run? Maybe github had a hiccup in connectivity? 

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by mperrin** [comment]
Trying again, after adding some more about Sphinx in the Travis conf file.

**Comment by mperrin** [comment]
Hurray, this all seems to be working now.

**Comment by bhilbert4** [comment]
Excellent! I'll merge it and then start looking into populating pages.

**Pull request merged**
