### PR TITLE
Mirage name change

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR completes the process of changing the name of the package from `nircam_simulator` to `mirage`. 

In addition, the code has been tweaked to make proper use of an environment variable, `MIRAGE_DATA`, which points to the collection of reference files that MIRAGE needs to function. I rearranged slightly the directory tree of the reference files, in order to be more consistent across instruments. I will send around, via email, the `MIRAGE_DATA` environment variable path that I have been using. After this update, there should no longer be path names anywhere in the repo.

I have tested these updates by making NIRCam imaging and wfss data. I have not yet tested NIRISS or FGS, but those are next on my to do list. I tested yaml_generator this morning, which has several small tweaks. 

Also, the `examples` directory has been moved up one level in the directory tree. I have updated our four notebooks to remove path names and make use of the environment variable. I successfully tested the three NIRCam science notebooks, however I wasn't able to test the OTE commissioning notebook since it points to data that I don't have. @laurenmarietta, could you test that one? 

I made some changes to the readme file reflecting all of this updating, but there is probably more that could go in there.

### CODE REVIEW

**Comment by laurenmarietta** [comment]
Hmm, here's an odd thing: in the PR for the OTE example notebook, I had originally included example data and made some changes to various scripts (https://github.com/spacetelescope/mirage/commit/334f074c00267afcaf8987db1049dcdb196674a2), but those changes seem to have been lost somehow...

Do you want me to re-implement those changes and re-add the data as part of this PR?

Besides that, I'm getting a strange error from the new SIAF path. Have you seen this before?

```
Traceback (most recent call last):

  File "/Users/lchambers/miniconda3/envs/OTECommSims/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-11-eee10a0dfabb>", line 2, in <module>
    nc_siaf = jwxml.SIAF(filename=siaf_file)

  File "/Users/lchambers/miniconda3/envs/OTECommSims/lib/python3.5/site-packages/jwxml-0.3.0-py3.5.egg/jwxml/siaf.py", line 477, in __init__
    self._tree = etree.parse(self.filename)

  File "src/lxml/etree.pyx", line 3425, in lxml.etree.parse

  File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument

  File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL

  File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile

  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFile

  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc

  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult

  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError

  File "/ifs/jwst/wit/mirage_data/nircam/reference_files/SIAF/NIRCam_SIAF_2018-01-08.csv", line 1
    Aperture Basic Info,,,,,Detector Frame,,,,Science Frame,,,,,,V-Frame,,Frame Relationships,,,,,,Vertices,,,,,,,,,,Science to Ideal Polynomial,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
                                                                                                                                                                                                                                     ^
XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1


```

**Comment by bhilbert4** [comment]
Definitely re-implement those changes and re-add the data for the notebook. I had a day-long fight with git on Friday over the renaming. It seemed to have remembered some commits, but forgotten others and treated them a conflicts that I had to re-fix. Strange that it also seems to have forgotten about your older commits though. I wonder if I was starting from an old copy of the OTE notebook somehow.

That's the first I've seen the SIAF error you pointed out. It looks like it's trying to read the SIAF file as if it is an xml rather than a csv?

**Comment by laurenmarietta** [comment]
Will do - and I realized that it was only one of the three scripts that lost its changes. So odd! Sorry to hear it was such a pain for you.

I think I figured out the SIAF error, it was a silly thing on my end. 

But I am noticing that the yaml_generator has changed in a way that is throwing an error. For example, it used to be that if there was no galaxy catalog provided, the yaml's galaxyListFile would just say `None`. Now the yaml is pointing every file that would have said `None` to `/Users/lchambers/TEL/mirage/examples/None`, which is not a file and is throwing an error. Do you have a quick idea as to what part of `yaml_generator` might be causing that? If not, I can investigate.

**Comment by laurenmarietta** [comment]
(But, once I manually fixed the `yaml` problem, everything ran great! Getting close.)

**Comment by bhilbert4** [comment]
Ah, I bet I know what's wrong with yaml_generator. I surrounded everything with an os.path.abspath. I bet it's now interpreting `None` as a file in the local directory. My reasoning behind that was that Armin has told me that if someone (like him) wanted to send a bunch of calls to Mirage to condor, it can't handle relative paths. So a catalog name like "../my_sources.cat" needs to be written out as a full path. So maybe I just need to check for `None` when doing that.

**Comment by laurenmarietta** [comment]
That sounds like it could be doing it! There might be something buggy happening, though, because I see you already have a 
```
if self.galaxyListFile[0] is not None
```
case checking, but it must not be working. 

I'll just commit the changes that I made, since everything else is going well now!

**Comment by bhilbert4** [comment]
I think I need to replace that `0` with an `i`, in addition to checking for `None`. Turns out I forgot that check in `apt_inputs.py`, which I'm updating now.

**Comment by Johannes-Sahlmann** [comment]
I am trying to run the test_apt.py script by @laurenmarietta using pytest but it fails because a file named `mirage/config/siaf_config.json` is missing. Where can I find that file?

**Comment by laurenmarietta** [comment]
Also, @bhilbert4, I think the `expand_env_var` method in `yaml_generator` might also be helpful if it were added to a file like a `utils.py` where it can be accessed outside of just that one script (#112)

**Comment by bhilbert4** [comment]
I was thinking that last night too. I'll add that to the list for work to be done in #112.

**Comment by bhilbert4** [comment]
It looks like your test functions for NIRISS and NIRCam are still called `test_fgs_imaging`.

**Comment by Johannes-Sahlmann** [comment]
Thanks for catching this.

**Pull request merged**
