### PR TITLE
Adds support for NIRISS SOSS mode

### PR DESCRIPTION
**Pull request by hover2pi**
This PR adds support for NIRISS SOSS simulations with the `soss_simulator` module and a few other supporting modules. The code is being ported from the `awesimsoss` package.

### CODE REVIEW

**Comment by hover2pi** [comment]
@bhilbert4 Minimal tests passing so this might be good to go. There are some files I generate before hand to speed up the calculations but I just stuck them in the `psf` directory until they can be added to the `MIRAGE_DATA` files. Let me know how you would like to organize this. Thanks!

**Comment by hover2pi** [comment]
OK @bhilbert4 , I think this is ready for a review!

**Comment by hover2pi** [comment]
@bhilbert4 I merged in `master` and made the updates we talked about. I think this is now... finally... truly... ready for a review.

**Comment by bhilbert4** [comment]
This looks good to me! I just ran a test using imaging mode, just to make sure everything was still fine there, and it was. I'll merge this now and we can deal with any future issues as they pop up.

**Pull request merged**
