### PR TITLE
Fix filenames with respect to sequence id and exposure number.

### LINKED ISSUE #349: File names of parallel exposures are wrong
The sequence id of parallel exposures has to be unequal to 1, but mirage currently sets it always to 1. 
The sequence id for the first parallel instrument should be 2.

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
This PR provides a preliminary fix to the sequence id and exposure number encoded in the output file name.
It does not solve the issue of setting the activity id correctly.

Closes #349 

Relates to #281

### CODE REVIEW

**Comment by Johannes-Sahlmann** [comment]
Thanks @bhilbert4 I think I solved the detector-related issue.

**Comment by Johannes-Sahlmann** [comment]
This originates in a part of `yaml_generator` that I did not write nor modify, and I suspect it is caused by the change to the `activity_id` setting. Maybe we should have a separate issue that can be tackled when we address the activity id?

**Comment by bhilbert4** [comment]
Sounds good to me. I haven't had any luck yet tracking down a description of how the activity ID is populated.

**Comment by bhilbert4** [comment]
From my inquires, it sounds like activity IDs are generated by OPGS. They are present in Visit files but nowhere else that I've found. It seems like we'd need some functions that look at things like dithers/slews and probably other things in order to correctly calculate the activity ID for a particular exposure. 

So in the meantime, I guess the question is, is it better to set the activity ID to 01 for everything, or to go back to incrementing for each exposure, which is closer to correct, but not quite.

**Comment by mperrin** [comment]
Activity IDs are part of the structure of the OSS visit files. They’re clearly labeled in those files, but may require some amount of reverse-engineering to recreate independent of that. For instance, slews and guide star acquisitions count as activities so those can increment the activity number without any exposure being taken. 

My recommendation would be let’s talk to Ilana Dashevsky to see if there is a good document summarizing how OPGS creates and assigns there. For each different APT template we may need to get a copy of a visit file created with that template and build some lookup table of what happens for that template...

**Comment by mperrin** [comment]
(I wrote my comment just above at the same time as you were writing; sorry if it’s a bit duplicative.)

Visit files are not ITAR sensitive. They can be and are posted to the outer space wiki, and I don’t see any reason examples couldn’t be posted here too.

**Comment by Johannes-Sahlmann** [comment]
I suggest that we keep the activity_id set to 1 until we figure it all out. 
JWST .vst files are not public and should therefore not be posted here (we had that disucssion for https://github.com/spacetelescope/jwst-visit-parser, too).

**Comment by Johannes-Sahlmann** [comment]
So, should we merge this?

**Comment by bhilbert4** [comment]
I think this is ready to merge, yes. Tackling the activity ID is going to be a whole separate effort.

**Pull request merged**
