### PR TITLE
[WIP]: Populate filter position,  pupil position, and target info header keywords

### LINKED ISSUE #390: TARGNAME hard coded to UNKNOWN
Currently the TARGNAME header keyword in data saved by obs_generator.py is hard coded to be UNKNOWN. This information is being extracted from input APT files, and should be passed on to the output data files.

### LINKED ISSUE #392: Missing NIRISS filter and pupil wheel position information
For NIRISS WFSS observations, the calibration pipeline needs to know the position of the filter and pupil wheel. This is in order to calculate the dispersion solution. These values should be in degrees, and represent the orientation of the filter and pupil wheels corresponding to each element in those wheels.

@KevinVolkSTScI provided a table with these values from OTIS testing, with one small update for GR700XD. This table comes from a technical report authored by Andre Martel.

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds some data to header keywords in the raw and linear files output by the observation generator. 

- The target name as entered by the user in the APT file is now saved to the TARGPROP keyword. (The TARGNAME keyword is left as 'UNKNOWN' since this is supposed to be a standard astronomical catalog name.)

- The target RA and Dec (TARG_RA, TARG_DEC) are now correctly populated, based on the value in the input APT file. Previously these were given the RA and Dec of the reference location for the aperture, which was incorrect.)

- The filter wheel and pupil wheel resolver locations are now saved to the FWCPOS and PWCPOS keywords for NIRISS observations only. These are needed to compute the dispersion solution for WFSS observations. The infrastructure is in place that these could easily be added for NIRCam observations in the future, if needed. They are kept out at the moment, rather than using dummy values in order to avoid confusion. The comment attached to those header keywords are 'NIRISS filter wheel position' and 'NIRISS pupil wheel position'. This could be confusing in a NIRCam file.
FWCPOS and PWCPOS values are stored in the new 'niriss_filter_and_pupil_wheel_position.txt' file in the `config` directory. 

As part of this fix, there have been several changes upstream. 

- The target RA and Dec are now saved in the Observation list file created by `generate_observationlist.py`. These values are then added to new elements in the input yaml files, called `Output:target_ra` and `Output:target_dec`. 

- `Output:target_name` is also a new entry in the yaml files.

Resolves #390 
Resolves #392

### CODE REVIEW

**Comment by bhilbert4** [comment]
One other new entry in the yaml files: `Reffiles:filter_wheel_positions`, which contains the name of the ascii file with the filter and pupil wheel positions for each optical element.

**Comment by KevinVolkSTScI** [comment]
I think it can just be merged.

**Comment by camipacifici** [comment]
Agree with Kevin. You can merge.
Thank you very much!

**Comment by bhilbert4** [comment]
Will do...as soon as I fix a failing test

**Comment by bhilbert4** [comment]
Tests are now passing. Merging so that others can try out the updates.

**Pull request merged**
