### PR TITLE
Fix incorrect galaxy position angles

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR fixes a bug in the orientations (position angles) of galaxies in cases where PAV3 is non-zero.

- [x] Still need to make sure the same bug does not apply to extended sources.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Extended sources look incorrect also. Need to fix.

**Comment by bhilbert4** [comment]
Both galaxy and extended sources now appear to be rotated correctly for given position angles and telescope PAV3.

**Comment by bhilbert4** [comment]
@hover2pi do you have a few minutes to give this a look? The important part of the change is the now-simpler equation for translating a galaxy's position angle relative to North into the angle between the semi-major axis and the detector x axis. I also had to use different equations for galaxies vs extended sources because Mirage assumes that the stamp image of an extended source is oriented North up.

**Review by hover2pi — APPROVED** [review]
Good to go!

**Comment by bhilbert4** [comment]
Thanks!

**Pull request merged**
