### PR TITLE
[WIP]: Catalog to hdf5

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds code for supporting the use of hdf5 files to pass SED curves to Mirage. This update is aimed primarily at WFSS mode simulations.

The user can provide an ascii source catalog, along with an optional dictionary containing source spectra, or an hdf5 file containing source spectra. The code then works to combine the information from these sources. Any spectra passed in via dictionary or hdf5 catalog are copied into a final hdf5 file. Any sources that are present in the ascii catalog but not the dictionary or hdf5 file have basic continuum spectra constructed. These spectra are then added to the final hdf5 file, which can be passed to the disperser package (NIRCAM_Gsim). 

Continuum spectra are estimated by interpolating between the provided filter magnitudes. In cases where only a single filter magnitude is given, the continuum is assumed to be flat.

The motivation behind this update is to make Mirage more flexible in terms of user inputs. If input spectra are provided in an hdf5 file, the disperser software requires a spectrum for all sources in the input catalog. With this update, users can provide spectra only for sources of interest, and spectra for background sources will be computed on the fly.

### CODE REVIEW

**Comment by bhilbert4** [comment]
Still to do:
Integrate these changes into `wfss_simulator.py` now that #254 has been merged.
Make sure that everything works with all catalog types.

**Comment by bhilbert4** [comment]
This PR addresses the WFSS part of the conversations in #157 and #227. Related use of hdf5 input files for imaging simulations will be addressed in a separate PR.

**Comment by bhilbert4** [comment]
I think this is ready for review. Other than the new options for inputs to the *wfss_simulator*, these changes should appear as fairly minor from the standpoint of what the user sees. But under the hood the interpolation that is used to construct SEDs has been moved from the disperser to the *wfss_simulator*. This should speed up the overall simulation process, and makes the inputs more flexible. 

Your hdf5 input file now no longer has to contain an SED for every object in your ascii catalog. So now you can add background sources without having to bother specifying a spectrum for them. And for sources that are included in the hdf5 file, you should now be able to use F_lambda (in CGS or MKS), F_nu (in CGS or MKS), or normalized units, and you can provide either wavelengths or frequencies (as long as you specify units).

I have updated the NIRISS WFSS notebook to highlight the changes. Do someone have time to run through the notebook and make sure everything makes sense and that there aren't any obvious errors in the outputs?
@KevinVolkSTScI @swara13 @camipacifici @jotaylor @NorPirzkal

**Comment by KevinVolkSTScI** [comment]
I can take a look at this later in the week.  If Swara or Camilla or Jo can look at it sooner I will defer to them.

**Comment by camipacifici** [comment]
I am planning to install this new version and go through the notebook this afternoon.

-----------------------------------------------------
Dr. Camilla Pacifici
JWST/NIRISS Instrument Scientist
Space Telescope Science Institute
(Muller S307)	

Office phone: 667 218 6543
cpacifici@stsci.edu
camilla.pacifici@gmail.com
-----------------------------------------------------

**Comment by bhilbert4** [comment]
Coming back to old PRs. Has anyone tried out these changes?

**Comment by camipacifici** [comment]
I can run your notebook with no problem. I have also created other simulations (direct images and WFSS) and I have found no problem when running all the steps. I am still testing the count rates as reported in issue #278.

**Pull request merged**
