### PR TITLE
Catalog generators

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR introduces code to help Mirage users create semi-realistic source catalogs.

This includes the ability to query (and cross-match) the 2MASS, GAIA, and WISE catalogs (in order to add real sources), as well as the Besancon model, which can be used to create a representative population of point sources. The Besancon model goes down to dimmer magnitudes  than the other catalogs, and can be used to fill in the background. 

In addition, the generation of extragalactic background sources is supported by querying the 3d HST catalog of the GOODS-S field, and placing the galaxies at random positions in the field, with small tweaks to magnitudes, Sersic indexes, etc. Currently this only works when requesting a catalog for an area smaller than the GOODS-S field, which is 606,909 arcsec^2 (roughly equal to a 6x6 grid of NIRCam LW detectors.)

Note that this code adds a new dependence to Mirage. The catalog creation function currently calls @Johannes-Sahlmann's  `distortion` package, which is not yet used by Mirage (although was planned to be, via #50). We will have to deal with this new dependence before merging.

Currently we still need to add tests for this new functionality. It would also be good to add some examples to a notebook.

Also still need to compare what the code does to options discussed in #184.

### CODE REVIEW

**Comment by KevinVolkSTScI** [comment]
We can take the usage of distortion.py out of the code if needed, it is used for convenience so that if the requested (RA,Dec) is near the pole things will still work properly.  It would require only small changes to the code to take it out.  However, it seems better to use this also in the general scene generation for the same reason.

**Comment by Johannes-Sahlmann** [comment]
I have migrated this functionality into pysiaf and it can be imported from there instead, since pysiaf is already a dependency of mirage: https://github.com/spacetelescope/pysiaf/blob/master/pysiaf/utils/projection.py

**Comment by bhilbert4** [comment]
@KevinVolkSTScI I'm doing a "final" clean-up of the catalog generation code, and putting together a notebook to show how to use it. I was wondering, the get_all_catalogs function currently returns a catalog that contains magnitudes in the requested filters, along with the original Besancon JHKL columns. Is there a reason you left JHKL in the catalog? If you think it's potentially useful for a user to have then I'm all for it. I was just confused to see those columns in there.

Also, I wrote an updated `combine_catalogs` function that uses astropy's `join` function, and more importantly, should work for all Mirage catalog types rather than just PointSourceCatalogs. As far as I can tell, your version of `combine_catalogs` was essentially a DIY version of astropy's `join`. I hope it's ok that I slotted the new version into the code. Right now I still have your function in the code. I just renamed it to `combine_catalogs_v0`.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 I left the Besancon JHKL values in the catalogue for testing to compare the output magnitudes with the input magnitudes and make sure that the transformation results are doing what I thought it should be doing.  If you are unhappy with this they can be removed, I just think it is useful information.

**Comment by bhilbert4** [comment]
No problem. We can leave them in then.

One other change I made yesterday: The Besancon query was being really finicky with the random coordinates I chose, and was failing with non-intuitive error messages. After some investigation, I added some checks, so that in the case of a Besancon failure, a catalog with a single star with magnitude=99 in all bands is returned. In that way a Besancon failure won't crash `get_all_catalogs`.

**Comment by bhilbert4** [comment]
Ok, let me know what you find. Right now I'm using `join` with `join_type='outer` and with `.filled()` tacked onto the end of the command, which seemed to be doing what I wanted in my tests.

**Comment by bhilbert4** [comment]
@KevinVolkSTScI do you consider this branch ready to merge? I've used all the functions you have written and they look good to me.

**Comment by KevinVolkSTScI** [comment]
From my point of view it is ready to merge.  The 2MASS/WISE/GAIA cross-matching may need some improvement later if I can figure out something to make it do better.

**Pull request merged**
