### PR TITLE
Add environment file

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR introduces an environment file in order to make installation of `mirage` and its dependencies easier. 

To use the environment file:

`conda env create -f mirage_environment.yml`

Next install the packages associated with `mirage`, using `python setup.py install`:
`mirage` : https://github.com/spacetelescope/mirage
`NIRCam_Gsim` : https://github.com/npirzkal/NIRCAM_Gsim
`GRISMCONF` : https://github.com/npirzkal/GRISMCONF

### CODE REVIEW

**Comment by bhilbert4** [comment]
After following the recipe above, I ran pytest on our tests (in the `pysiaf-integration` branch where the tests have been fixed) and everything passed.

**Comment by KevinVolkSTScI** [comment]
I tried this on witserv3, which is where I normally run and test mirage because the supporting files are there, and I get errors:

witserv3 kevin > conda env create -f mirage_environment.yml

SpecNotFound: Can't process without a name

It wants a name so I tried with a name option (although the documentation for conda says that the name is takenf rom the .yml file...)

witserv3 kevin > conda env create -f mirage_environment.yml -n test_mirage

SpecNotFound: Invalid name, try the format: user/package

I have no idea what the problem is.  The conda environment on witserv3 should be up to date so I was not expecting any surprises in testing it.

**Comment by KevinVolkSTScI** [comment]
The previous comment was caused by my error:  I did not have the mirage_environment.yml file in the directory where I was trying to run the conda command.

However, once I fixed that it still fails on witserv3 with the following message--

witserv3 test_mirage > conda env create -f mirage_environment.yml

CondaValueError: invalid package specification: simplegeneric=0.8.1.tools=3.4.12.dev33+g349cb3c=py36_0

**Comment by bhilbert4** [comment]
Make sure you are outside of your environments when you do that. I just tried that on witserv and found that I was significantly behind. I also found that my default on witserv is python 2.7. I haven't tested to be sure, but my expectation is that 'mirage' will not work in python 2.

**Comment by KevinVolkSTScI** [comment]
After doing "conda update conda" the same error message is seen when I try to do the installation with the .yml file.  So it did not fix the problem.

**Comment by KevinVolkSTScI** [comment]
I tried this out for NIRISS and got an error.  The python commands used and the results are:

witserv3 test_mirage > python
Python 3.5.5 |Anaconda, Inc.| (default, Apr 26 2018, 13:47:34) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mirage.psf.psf_library as psf_library
>>> nis = psf_library.CreatePSFLibrary("NIRISS")
>>> nis.create_files()

Starting filter: F090W
  Running detector NIS
Pysynphot unavailable (or invalid source supplied)!   Assuming flat # of counts versus wavelength.
CAUTION: Just interpolating rather than integrating filter profile, over 21 steps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-2.0.1-py3.5.egg/mirage/psf/psf_library.py", line 258, in create_files
    final_list = self._run_files(self.filter_list, self.detector_list)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-2.0.1-py3.5.egg/mirage/psf/psf_library.py", line 316, in _run_files
    psf = self.webb.calc_psf(fov_pixels=self.fov_pixels, oversample=self.oversample)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/webbpsf/webbpsf_core.py", line 797, in calc_psf
    psf[ext_new].header["EXTNAME"] = psf[ext].header["EXTNAME"][0:4] + "DIST"  # change extension name
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 317, in __getitem__
    raise e
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 313, in __getitem__
    self._positive_index_of(key))
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py", line 1090, in _try_while_unread_hdus
    return func(*args, **kwargs)
IndexError: list index out of range

Any ideas about what the problem is?  This is being run on witserv3, in case that may affect the results (although I think it should not matter).

**Comment by bhilbert4** [comment]
Ok. In that case it might be worth opening a new issue and tagging @shanosborne since she's the expert on `psf_library.py`.

**Comment by shanosborne** [comment]
@KevinVolkSTScI, this error is the same error that you originally pointed out to the WebbPSF team and it is fixed by having the development version of WebbPSF. This version was not automatically downloaded when you create your environment because you need the GitHub dev version of WebbPSF, which is past the latest conda version. We are working toward releasing WebbPSF 0.8.0 which will contain this new update (so we can include it in the mirage environment file), but for now you'll have to clone the WebbPSF repo

**Comment by KevinVolkSTScI** [comment]
Sorry, I intended to post this under the PSF library issue but somehow it got here instead.

**Comment by KevinVolkSTScI** [comment]
OK given Sharron's comment this is because I have a mirage testing environment and a webbpsf testing environment in conda with the latter environment being where I have the fix in webbpsf.  I was running in the mirage testing environment.

**Comment by laurenmarietta** [comment]
Is this file intended to only be used for Mac machines? I ran the environment file on a Linux server and got this error:
```
NoPackagesFoundError: Package missing in current linux-64 channels: 
  - libgcc 4.8.5 hdbeacc1_10
```
This error went away when I updated `conda` from 4.3 to 4.5, but then I got this:
```
ResolvePackageNotFound: 
  - cffi==1.11.5=py36h342bebf_0
  - kiwisolver==1.0.1=py36h0a44026_0
  - cytoolz==0.9.0.1=py36h1de35cc_1
  - yaml==0.1.7=hc338f04_2
  - jsonschema==2.6.0=py36hb385e00_0
  - lxml==4.2.3=py36hef8c89e_0
  - freetype==2.9.1=hb4e5f40_0
  - appnope==0.1.0=py36hf537a9a_0
  - tblib==1.3.2=py36hda67792_0
  - jpeg==9b=he5867d9_2
  - zlib==1.2.11=hf3cbc9b_2
  - tk==8.6.7=h35a86e2_3
  - sqlite==3.24.0=ha441bb4_0
  - libedit==3.1.20170329=hb402a30_2
  - libgfortran==3.0.1=h93005f0_2
  - h5py==2.8.0=py36h3c9e6ae_0
  - pandas==0.23.3=py36h6440ff4_0
  - libgcc==4.8.5=hdbeacc1_10
  - libtiff==4.0.9=hcb84e12_1
  - wcwidth==0.1.7=py36h8c6ec74_0
  - cryptography==2.2.2=py36h1de35cc_0
  - libxslt==1.1.32=hb819dd2_0
  - numpy-base==1.14.3=py36h479e554_1
  - libffi==3.2.1=h475c297_4
  - libiconv==1.15=hdd342a3_7
  - pillow==5.2.0=py36hb68e598_0
  - click==6.7=py36hec950be_0
  - pygments==2.2.0=py36h240cd3f_0
  - prompt_toolkit==1.0.15=py36haeda067_0
  - readline==7.0=hc1231fa_4
  - markupsafe==1.0=py36h1de35cc_1
  - pywavelets==0.5.2=py36h1d22016_2
  - libpng==1.6.34=he12f830_0
  - scipy==1.1.0=py36hf1f7d93_0
  - ipython_genutils==0.2.0=py36h241746c_0
  - partd==0.3.8=py36hf5c4cb8_0
  - pandoc==2.2.2=hde52d81_1
  - hdf5==1.10.2=hfa1e0ec_1
  - openssl==1.0.2o=h26aff7b_0
  - cython==0.28.4=py36h0a44026_0
  - matplotlib==2.2.2=py36hbf02d85_2
  - libxml2==2.9.8=hab757c2_1
  - icu==58.2=h4b95b61_1
  - ncurses==6.1=h0a44026_0
  - python==3.6.6=hc167b69_0
  - scikit-image==0.14.0=py36h0a44026_1
  - xz==5.2.4=h1de35cc_4
  - tornado==5.0.2=py36h1de35cc_0
  - traitlets==4.3.2=py36h65bd3ce_0
  - mkl_random==1.0.1=py36h5d10147_1
  - libcxxabi==4.0.1=hebd6815_0
  - msgpack-python==0.5.6=py36h04f5b5a_0
  - pickleshare==0.7.4=py36hf512f8e_0
  - locket==0.2.0=py36hca03003_1
  - psutil==5.4.6=py36h1de35cc_0
  - mkl_fft==1.0.4=py36h5d10147_1
  - libcxx==4.0.1=h579ed51_0
  - cycler==0.10.0=py36hfc81398_0
  - pyyaml==3.13=py36h1de35cc_0
  - numpy==1.14.3=py36h9bb19eb_1
```
which StackOverflow suggests is a platform-related problem.

It looks like this could maybe be fixed by generating a file without any build information:
`conda env export --no-builds > environment.yml`
as seen here: https://github.com/conda/conda/issues/6073

**Comment by bhilbert4** [comment]
I got the same error this morning. I think the problem is the `jwst` package, which does have different versions for osx and linux. I did use the osx version for the environment file. So I created one using the linux version tonight. The `jwst` version looks exactly the same in that version, but I do see other differences. I'll try that out in the morning, as well as the version without build info.

I also noticed that the osx file is missing `pysynphot`. I figured that would be installed along with `webbpsf`, but it seems like it wasn't. I'll also add that in to the file tomorrow.

**Comment by KevinVolkSTScI** [comment]
I also got the above set of "ResolvePackageNotFOund" errors on witserv2 and witserv3 this morning when I tried the conda environment build again.  At a guess, this is due to updating conda yesterday.

**Comment by bhilbert4** [comment]
Ok, try out these updated environment files. I tried the `no-builds` option, but still got errors with the linux file. So I ended up creating separate linux and OSX files from the linux and OSX versions of jwst. I also added `pysynphot` to both. I was able to successfully use these to create new environments on my Mac laptop as well as on witserv3.

**Comment by bhilbert4** [comment]
@laurenmarietta, yes, that was intentional. The other file creates an environment called `mirage_osx`. But in both cases the name of the environment can be changed by editing the top line of the environment file before calling `conda create env`

So I found out yesterday that the version of the `jwst` package referenced by these environment files has a bug. It's not in a part of `jwst` that `mirage` uses (or will ever use), but it still seems like we shouldn't point to it. I'm talking to some of the developers to see if they recommend pointing to the latest stable released version, or to the very latest version. If we use the latter, then it seems like there is no OSX/Linux dependency and we'd only need a single environment file.

**Comment by laurenmarietta** [comment]
Hmm, I just found something questionable: the `pysiaf` requirements are not consistent between OSes? Also, the OSx pysiaf requirement is 0.1.12, when it seems like it has only be released to 0.1.11?

**Comment by bhilbert4** [comment]
pysiaf 0.1.12 must be released. Or at least, conda tells me that's the version that was installed through conda. I can't remember if I made the linux file just a little earlier? Maybe 0.1.12 was released between my creation of the two environment files? Or maybe for some reason linux still needs 0.1.11? @Johannes-Sahlmann, can you clear up this confusion?

**Comment by Johannes-Sahlmann** [comment]
pysiaf 0.1.12 is the current version on pypi https://pypi.org/search/?q=pysiaf

I am not aware of any differences with respect to operating systems.

**Comment by Johannes-Sahlmann** [comment]
Something is not right. I suspect that I issued 0.1.12 only locally and then made the pypi upload from my disk. This can explain why https://github.com/spacetelescope/pysiaf/releases is out of sync with pypi.
I wanted to clean this (release) process up anyways, and this is clearly a strong motivation. My apologies.

**Comment by bhilbert4** [comment]
@Johannes-Sahlmann, am I right that version 0.1.12 will contain the corrected NIRCam coefficients (that solve the round trip error)?

**Comment by Johannes-Sahlmann** [comment]
No. The updated NIRCam SIAF has not been ingested in the PRD yet.

**Comment by bhilbert4** [comment]
Ok thanks. Do you have an estimate of when the updated coefficients will be released?

**Comment by bhilbert4** [comment]
Added astroquery to the OSX and Linux versions, and added jupyter notebook to the Linux version. (#164)

**Comment by laurenmarietta** [comment]
Whoops, I forgot that this PR hadn't been merged yet - I would have just commented those here. Thanks for adding them!

**Pull request merged**
