### PR TITLE
Keep POM mode simulation seed images as 2322x2322 pix

### LINKED ISSUE #604: In NIRISS WFSS or POM modes the direct images are limited to the normal detector area
In NIRISS POM mode or WFSS mode the direct image simulation should be 2322x2322 pixels.  It used to be that way, say 1 year ago.  Currently the seed images for these cases have the central 2048x2048 pixels of the seed image populated but the surrounding 137 pixel border where the POM is present but the images do not fall onto the detector is all zero.  I had thought that this was corrected, but the Mirage version as of a few days ago shows this problem.  My old Mirage version of 13 February 2020 does not have this issue and the images are fully populated.

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR fixes an oversight from #523  where POM transmission images were introduced. For "pom" mode simulations in Mirage, the desired output is a seed image that is larger than the detector, so that sources just off the edge of the detector can be seen. When we introduced the POM transmission images, the pom mode simulations were lumped in with imaging mode simulations, which are cut down to the detector size of 2048x2048 pixels.

This PR reverses that, and returns NIRISS pom mode simulations to 2322x2322 pixels. Note that the pom mode seed image is saved in a file with the suffix _pom_seed_image.fits. Mirage then does go on to crop this image to the nominal 2048x2048 size, and save that as the usual seed image in a file with the usual filename, with siffux _final_seed_image.fits.

Resolves #604

### CODE REVIEW

**Comment by KevinVolkSTScI** [comment]
I tried running a model with mode=POM and it crashed.  The simulation is for F158M.  The error message is

2021-05-28 17:33:43,592 - root - CRITICAL - Traceback (most recent call last):
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/logging/logging_functions.py", line 111, in wrapped
    func(*args, **kwargs)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/seed_image/catalog_seed_image.py", line 432, in make_seed
    self.pom_file = os.path.join(self.basename + '_' + self.params['Readout'][slf.usefilt] + '_pom_seed_image.fits')
AttributeError: 'Catalog_seed' object has no attribute 'usefilt'

2021-05-28 17:33:43,592 - stpipe - CRITICAL - Traceback (most recent call last)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/logging/logging_functions.py", line 111, in wrapped
    func(*args, **kwargs)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/seed_image/catalog_seed_image.py", line 432, in make_seed
    self.pom_file = os.path.join(self.basename + '_' + self.params['Readout'][slf.usefilt] + '_pom_seed_image.fits')
AttributeError: 'Catalog_seed' object has no attribute 'usefilt'

2021-05-28 17:33:43,592 - stpipe - CRITICAL - Traceback (most recent call last)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/logging/logging_functions.py", line 111, in wrapped
    func(*args, **kwargs)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/seed_image/catalog_seed_image.py", line 432, in make_seed
    self.pom_file = os.path.join(self.basename + '_' + self.params['Readout'][slf.usefilt] + '_pom_seed_image.fits')
AttributeError: 'Catalog_seed' object has no attribute 'usefilt'

2021-05-28 17:33:43,592 - root - CRITICAL - CRASHED
2021-05-28 17:33:43,592 - stpipe - CRITICAL - CRASHED
2021-05-28 17:33:43,592 - stpipe - CRITICAL - CRASHED
Traceback (most recent call last):
  File "../runmodels.py", line 66, in <module>
    t1.create()
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/imaging_simulator.py", line 69, in create
    cat.make_seed()
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/logging/logging_functions.py", line 111, in wrapped
    func(*args, **kwargs)
  File "/home/kvolk/anaconda3/envs/mirage_28may2021/lib/python3.7/site-packagesmirage/seed_image/catalog_seed_image.py", line 432, in make_seed
    self.pom_file = os.path.join(self.basename + '_' + self.params['Readout'][slf.usefilt] + '_pom_seed_image.fits')
AttributeError: 'Catalog_seed' object has no attribute 'usefilt'

If you wish to look at the .yaml file it is in /ifs/jwst/wit/niriss/kevin/focus_car_second_new_field/field_exposure_pom/ and the file is jw01085001001_01101_00001_nis.yaml.

**Comment by KevinVolkSTScI** [comment]
The same parameters work fine with the mode changed to "imaging" (I also turned off the ghosts to save time...).

**Comment by bhilbert4** [comment]
It looks like you're still pointing to the old version of the code.  The line: 
```self.pom_file = os.path.join(self.basename + '_' + self.params['Readout'][slf.usefilt] + '_pom_seed_image.fits')```
has now been replaced with:
```self.pom_file = os.path.join(self.basename + '_' + usefilt + '_pom_seed_image.fits')```
See here: https://github.com/spacetelescope/mirage/blob/master/mirage/seed_image/catalog_seed_image.py#L436

**Comment by KevinVolkSTScI** [comment]
This installation was done this afternoon after you posted the fix.  And I went back to conda "base" before I did the installation.  So I am puzzled that it was the old version...I will try again later.

**Comment by KevinVolkSTScI** [comment]
Doing another installation and rerunning the test showed that it worked as expected.

**Pull request merged**
