### PR TITLE
Add convenience functions for computing PA V3 values for roll_angle input

### PR DESCRIPTION
**Pull request by mperrin**
Adds functions to compute nominal V3 position angle for a given target on a given date. These rely on the [JWST GTVT](https://github.com/spacetelescope/jwst_gtvt) to calculate the nominal roll angle on some given date. 

Documentation updated to describe these functions and show example code.  

Thanks to @mfixstsci for help with the GTVT, including some tweaks to that codebase to enable this usage.

### CODE REVIEW

**Comment by mperrin** [comment]
I think it doesn’t need to be a required dependence, since it’s only needed for this one function (and it’s optional to use that function too). 

But that said, it’s a simple install via either conda or pip so not a big deal to add as a dependency if you prefer.

**Comment by bhilbert4** [comment]
Makes sense to me. Maybe just add a note in the documentation where it's called that you'll need to install jwst_gtvt first?

**Comment by mperrin** [comment]
Yes that was my intent with this sentence I added in the docs:
> These rely on the `JWST general target visibility tool <https://github.com/spacetelescope/jwst_gtvt>`_, which you must have installed to use this feature.

Is that not clear enough? I can rephrase if you have any suggestions.

**Comment by bhilbert4** [comment]
That looks good to me.

**Pull request merged**
