### PR TITLE
Enable Niriss wfss

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR makes some small changes to the code to enable NIRISS WFSS mode simulations.

NIRISS should now be supported in the same way that NIRCam WFSS is at the moment. Input files that specify 'wfss' mode and with 'grism_direct_image' set to True can be used by wfss_simulator.py to create:

1. Direct (undispersed) noiseless "seed images". These are inputs to the disperser which creates:
2. A noiseless dispersed seed image. This is combined with a dark ramp and has noise/CRs added to produce
3. A DMS-formatted raw (uncal) or linearized exposure.

There are some limitations at the moment on how this is used that I'll be addressing in the near future. At the moment in order to produce a dispersed exposure, you need as input multiple direct seed images through different filters (and with identical pointings). This is because the disperser takes the broadband magnitude of each source in the multiple filters and interpolates to create the continuum of the source. (In the future you will be able to input a single direct seed image and an hdf5 file containing a spectrum for the object, including emission/absorption lines.) 

So the way it is set up currently, you can't go straight from APT file -> yaml input files -> simulated data unless your proposal gets direct images of a given field through multiple filters.

PR #233 contains the updated code for producing the correct yaml input files from an input NIRISS WFSS APT file. This code should be merged soon. In the meantime, if you don't want to check out multiple branches of Mirage but you have APT files that you want me to run through, let me know.

If you're interested in testing this out, let me know. I can pass along the little scripts I was using today to get things working. They should serve as a very basic example.

I 'll also update the WFSS example notebook. It needs some minor updates to reflect some updates I've made in the last week or so.

@jotaylor @NorPirzkal

### CODE REVIEW

**Comment by bhilbert4** [comment]
Ok, my previous message that things were ready to test was a little premature. Now that the WFSS template yaml generator code (#233 ) has been merged and is available, and with some further tweaks to inputs, I think things are now ready for testing. 

In this PR, I've added a notebook and some associated input data that should hopefully be useful for showing how to create WFSS yaml inputs and then run them through Mirage. (examples/NIRISS_WFSS_data_creation_example.ipynb) 

I was able to successfully run the notebook last week. Let me know if you run into problems. @NorPirzkal, this is basically a simplified version of your notebook, where a lot of the code you were using is wrapped up into **wfss_simulator.py**.

@jotaylor @KevinVolkSTScI

**Comment by KevinVolkSTScI** [comment]
Trying a simple test case with the new branch led to an error:

Requested readout pattern NISRAPID is valid. Using nframe = 1 and nskip = 0
Frametime is 13.763785
Base cosmic ray probability per pixel per second: 4.4704272843552845e-06
Integration 0:
Traceback (most recent call last):
  File "./runmodels.py", line 47, in <module>
    t1.create()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/imaging_simulator.py", line 77, in create
    obs.create()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 972, in create
    simexp, simzero = self.add_crs_and_noise(self.seed)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 165, in add_crs_and_noise
    ramp, rampzero = self.frame_to_ramp(inseed)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 1605, in frame_to_ramp
    poissonsignal = self.do_poisson(deltaframe, self.params['simSignals']['poissonseed'])
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/ramp_generator/obs_generator.py", line 1436, in do_poisson
    signalgain = signalimage * self.gainim
ValueError: operands could not be broadcast together with shapes (2322,2322) (2048,2048) 

It is clear what is going on.  The code is assuming that the signalimage is 2048x2048 as it normally would be, but the oversized POM image is being used.  I took a quick look at the code, but it is not one of the places where I put in checks for the mode being "pom" for NIRISS where I handled this difference.  Lines 182 and 183 of catalog_seed_image.py are probably where the fix needs to be made.  Currently that is

        if self.params['Inst']['mode'] in ["pom"]:
            self.seedimage, self.seed_segmap = self.extract_full_from_pom(self.seedimage, self.seed_segmap)

but it needs to include the NIRISS/WFSS case (assuming that this does not mess up other aspects of the WFSS case...I cannot be sure of that).

**Comment by bhilbert4** [comment]
I'll take a look at this tomorrow. By the time the **obs_generator** is being used, the seed image should be back down to 2048x2048. The fact that it's not suggests that the seed image coming out of the disperser wasn't cropped. Were you running **wfss_simulator.py**, or just calling the three main steps of Mirage? If the latter, then I the seed image would be too large going into the **obs_generator** and I would expect Mirage to fail in the way you're seeing.

**Comment by bhilbert4** [comment]
I should also mention that a WFSS seed image, as it comes out of **catalog_seed_generator**, should be 2322x2322.

**Comment by KevinVolkSTScI** [comment]
I was just running the simulator via the ImgSim function.  I do not try to use the "internal" functions such as wfss_simulator.py.
It is curious that this failed and your test did not, but that is what testing is for....

**Comment by bhilbert4** [comment]
WFSS files have to be run through **wfss_simulator.py**, as that is what calls the disperser software (after generating the seed image). See the notebook with this branch for an example. I suppose we could add an overall wrapper that takes a list of yaml files, inspects each one for the mode, and calls **imaging_simulator.py** for the imaging yamls, and **wfss_simulator.py** for the wfss yamls.

**Comment by KevinVolkSTScI** [comment]
OK I will change my code to call one branch or the other depending on the mode and run again.

**Comment by KevinVolkSTScI** [comment]
I produced a set of imaging scene .yaml files (f090w_scene.yaml to f200W_scene.yaml) and ran Mirage to make the oversized NIRISS scene images as input for trying wfss_simulator, but it fails.  I do not understand why trying to define the wfss_simulator object as in the notebook fails for me.  Any thoughts on what to do?

The terminal output is:

witserv3 wfss_confirmation > python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mirage import wfss_simulator
>>> import os
>>> import fnmatch
>>> allfiles = os.listdir('./')
>>> goodfiles = fnmatch.filter(allfiles,'f*scene.yaml')
>>> print(goodfiles)
['f200w_scene.yaml', 'f090w_scene.yaml', 'f115w_scene.yaml', 'f140m_scene.yaml', 'f150w_scene.yaml', 'f158m_scene.yaml']
>>> w1=wfss_simulator.WFSSSim()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'paramfiles'
>>> w1=wfss_simulator.WFSSSim()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'paramfiles'
>>> w1=wfss_simulator.WFSSSim(paramfiles=goodfiles)
when you go to make the direct seed image in the case where a wfss yaml is provided
catalog_seed_image will need to ignore the grism name
This should be a change to catalog_seed_image? or modify the yaml here? Probably the former
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/wfss_simulator.py", line 104, in __init__
    self.paramfiles = self.find_param_info()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/wfss_simulator.py", line 325, in find_param_info
    raise ValueError(("WARNING: No WFSS mode parameter files found. One of the parameter "
ValueError: WARNING: No WFSS mode parameter files found. One of the parameter files must be wfss mode in order to define grism and crossing filter.
>>> goodfiles.append('jw00042002001_01102_00002_nis_new.yaml')
>>> w1=wfss_simulator.WFSSSim(paramfiles=goodfiles)
when you go to make the direct seed image in the case where a wfss yaml is provided
catalog_seed_image will need to ignore the grism name
This should be a change to catalog_seed_image? or modify the yaml here? Probably the former

**Comment by bhilbert4** [comment]
I see I forgot to remove some print statements from development. It looks like things were working the final time you called it, after adding the WFSS yaml file to the list. Or is there a traceback that was cut off?

**Comment by KevinVolkSTScI** [comment]
I assumed that it failed because of the message.  There was no traceback beyond what I posted.  The call did not seem to do anything.  How do I tell if it worked?

**Comment by bhilbert4** [comment]
Hmm. It should have printed more than that to the screen. You should have, pretty quickly, seen the same output that you normally see from **catalog_seed_generator.py**.

**Comment by KevinVolkSTScI** [comment]
I did not see anything that indicated that the program was working.  No output files were produced.  One possible issue is that I already ran the seed images in the 6 filters from the *_scene.yaml files before I tried doing the test.  However I would expect it would just overwrite the previous output files.

**Comment by bhilbert4** [comment]
Yes, it would have overwritten the files rather than stopping and doing nothing. If you send me your yaml files, I can give it a try and see what happens.

**Comment by KevinVolkSTScI** [comment]
The files are all sitting in /ifs/jwst/wit/niriss/kevin/focus_car_new_field/wfss_confirmation so you can get to them.  The jw*.yaml files in the directory come from a commisioning APT file using WFSS mode, so I ran the code on the direct image file jw00042002001_01101_00001_nis_new.yaml which makes a direct image of size 2048x2048.  The f*_scene.yaml files make the oversized POM field seed images.  I think the only other thing you need to get to test it is the source list file focus_field_all_filters.list.

**Comment by bhilbert4** [comment]
Ok, I found the problem. The **wfss_simulator** assumed that input yamls would be either WFSS or imaging mode. So the pom mode files were being ignored. I made (and just pushed) a small update to be able to use pom, and I got your case to work using the code below. Note that with the large number of stars in there, it takes a while (>30min) to run, even with the **source_stamps_file** option set to None.

```
from glob import glob
from mirage import wfss_simulator, imaging_simulator

yaml_files = glob('f*scene.yaml')
yaml_files = ['jw00042002001_01102_00002_nis_new.yaml'] + yaml_files
sim = wfss_simulator.WFSSSim(yaml_files)
sim.create()
```


My next piece of work, which I'll do in a separate PR, will be to write some code that will take a catalog file that contains magnitudes for multiple filters, and have it read the file in, do the interpolation, create continuum spectra for all objects, and write those spectra to an hdf5 file. Once that is working, you'll be able to call the **wfss_simualtor** with a single yaml file, as an appropriate hdf5 file will be created on the fly from the catalog listed in the yaml file. And at that rate you won't need to worry about having multiple yaml files/seed images at exactly the same pointing in a range of filters.

**Comment by KevinVolkSTScI** [comment]
I will try this out.  However a question comes to mind.  If I set the mode to imaging does the code create POM sized seed images in the WFSS case?  Or does it only make the regular sized images?  I had assumed that like the imaging simulator part of Mirage one gets the 2048x2048 pixel seed image when the mode is imaging in the .yaml files, which would be wrong for WFSS mode.

**Comment by bhilbert4** [comment]
When you provide a list of yaml files to **wfss_simulator**, it looks though them and:
1. Uses the first file in the list to determine instrument and module (if necessary)
2. For each imaging or pom mode file, it creates a copy of the file, and sets the mode to "imaging" and sets grism_source_image to True, which will create the properly sized seed image for the disperser.
3. It looks in the WFSS mode yaml file to determine the grism, dispersion direction, and crossing filter to use for dispersing.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 I made some new .yaml files that have mode = imaging and tried to rerun the WFSS simulation.  It produces some tmp_update_to_wfss_mode_*.yaml files for the 6 imaging inputs, but it still does not go ahead and make any models.

>>> print(goodfiles)
['f200w_scene1.yaml', 'f150w_scene1.yaml', 'f090w_scene1.yaml', 'f115w_scene1.yaml', 'f140m_scene1.yaml', 'f158m_scene1.yaml', 'jw00042002001_01102_00002_nis_new.yaml']
>>> w1=wfss_simulator.WFSSSim(paramfiles=goodfiles)
when you go to make the direct seed image in the case where a wfss yaml is provided
catalog_seed_image will need to ignore the grism name
This should be a change to catalog_seed_image? or modify the yaml here? Probably the former
>>> 

This is in the same directory as before if you wish to look at the input files.

witserv4 wfss_confirmation > pwd
/ifs/jwst/wit/niriss/kevin/focus_car_new_field/wfss_confirmation
witserv4 wfss_confirmation > lst
total 8563232
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f158m_scene1.yaml
drwxrwxr-x. 4 kvolk   wit          5277 Feb 18 10:51 .
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f140m_scene1.yaml
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f115w_scene1.yaml
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f090w_scene1.yaml
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f150w_scene1.yaml
-rwxrwxr-x. 1 kvolk   wit          4962 Feb 18 10:51 tmp_update_to_wfss_mode_f200w_scene1.yaml
-rw-r--r--. 1 kvolk   wit         10707 Feb 18 10:46 f200w_scene1.yaml
-rw-r--r--. 1 kvolk   wit         10707 Feb 18 10:45 f158m_scene1.yaml

**Comment by bhilbert4** [comment]
@KevinVolkSTScI there's something strange going on here. I just ran your case above and it seemed to work fine (although I stopped the run after the direct seed images were created). The latest commits shouldn't affect imaging mode files, but it might be worth pulling them down if you haven't already.

**Comment by pllim** [comment]
Thanks for pointing me to this, @bhilbert4 ! @eteq , would this satisfy your science requirements?

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 I tried installing this branch on my Mac laptop and running one of my full frame extended source models for just NIRISS imaging.  While the code did not crash the way it does on witserv, it did not do the right thing.  It tells me that there is no extended source in the field.  Here is part of the messages that came back:

Requested readout pattern NISRAPID is valid. Using the nframe = 1 and nskip = 0
No point source catalog provided in yaml file.
No galaxy catalog provided in yaml file.
SIAF: Requested NIS_CEN   got NIS_CEN
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
output dimensions are: [2322 2322]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Frametime is 10.736770000000002
Creating signal rate image of synthetic inputs.
Extended source list input positions assumed to be in units of pixels.
After extended sources, max index is 1
WARNING: Catalog scene1.list does not have a magnitude column called niriss_f150w_magnitude, but does have a generic 'magnitude' column. Continuing simulation using that.
Number of extended sources found within the requested aperture: 0
Warning: no non-sidereal extended sources within the requested array.
The extended source image option is being turned off

On witserv with the same input files and (nominally) the same version of Mirage the code finds 1 extended source in the field as expected.

The extended image file is as follows:

(mirage_linux_feb4_2019) witserv3 wfss_confirmation > more scene1.list
#
# vegamag
# position_pixels
#
x_or_RA y_or_Dec filename magnitude pos_angle
1024.0 1024.0 scene_image_generation/pos1_F150W_gr150r_detectorfield.fits None 0.0

I am still waiting to see whether the run on my machine here will work or whether it will fail with the same problem of mis-matched image sizes between the seed image and the gain image.  Any run on my laptop here is terribly slow.  Whatever happens with the gain, not applying the extended source image is a bug somewhere.  The seed image is going to have no signal in it as far as I can see from the output.  The file requested in the scene_image_generation directory is there.  I am unable to explain what is happening.

I will also try running the WFSS case but that will take much longer to test because multiple exposures need to be simulated.  I was starting with what should be a simple case....

**Comment by bhilbert4** [comment]
@KevinVolkSTScI I see the same thing. Zero extended sources found in the field of view. I'll look into it, although separately from this PR since that issue is with extended sources rather than WFSS specifically. One item to note: make sure you have the **grism_source_image** parameter in the yaml file set to False in this case. Your file currently has it set to True, which is why Mirage is making a 2322x2322 seed image.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 Thanks, I just fixed this grism_source_image = True thing and retried the calculations on witserv, and the models are running now.  I looked at this parameter last night and thought it was set properly but I was wrong.
On witserv the code does pick up the extended source image properly.

**Comment by KevinVolkSTScI** [comment]
Attempting to run the WFSS option for NIRISS on witserv3 currently produces the following:

witserv3 wfss_confirmation > python runwfss.py
['f200w_scene.yaml', 'f090w_scene.yaml', 'f115w_scene.yaml', 'f140m_scene.yaml', 'f150w_scene.yaml', 'f158m_scene.yaml', 'jw00042002001_01102_00002_nis_new.yaml']
when you go to make the direct seed image in the case where a wfss yaml is provided
catalog_seed_image will need to ignore the grism name
This should be a change to catalog_seed_image? or modify the yaml here? Probably the former
change me for niriss
Requested readout pattern NISRAPID is valid. Using the nframe = 1 and nskip = 0
No galaxy catalog provided in yaml file.
SIAF: Requested NIS_CEN   got NIS_CEN
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
output dimensions are: [2322 2322]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Frametime is 10.736770000000002
Creating signal rate image of synthetic inputs.
Point list input positions assumed to be in units of RA and Dec.
Using niriss_f150w_magnitude column in focus_field_all_filters.list for magnitudes
Expected time to process 3654 sources: 35.93 seconds (0.60 minutes)
Number of point sources found within the requested aperture: 976
Seed image is 2D.
Seed image and segmentation map saved as /ifs/jwst/wit/niriss/kevin/focus_car_new_field/wfss_confirmation/jw00042002001_01102_00002_nis_uncal_F150W_seed_image.fits
Seed image, segmentation map, and metadata available as:
self.seedimage, self.seed_segmap, self.seedinfo.
Background file is f150w_gr150r_medium_background.fits
orders: ['A', 'B', 'C', 'D', 'E']
Warning: SED Extrapolation turned on.
We have  778 Objects
dir image: /ifs/jwst/wit/niriss/kevin/focus_car_new_field/wfss_confirmation/jw00042002001_01102_00002_nis_uncal_F150W_seed_image.fits
Loaded /ifs/jwst/wit/niriss/kevin/focus_car_new_field/wfss_confirmation/jw00042002001_01102_00002_nis_uncal_F150W_seed_image.fits wavelength: 1.4935 micron
Dispersing  1 of 778 ID: 4.0
238 pixels loaded for dispersion...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/NIRCAM_Gsim-1.1-py3.6-linux-x86_64.egg/NIRCAM_Gsim/observations/observations.py", line 14, in helper
    p = dispersed_pixel(x0s,y0s,f,order,C,ID,extrapolate_SED=extrapolate_SED)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/NIRCAM_Gsim-1.1-py3.6-linux-x86_64.egg/NIRCAM_Gsim/disperse/disperse.py", line 47, in dispersed_pixel
    f = interp1d(f0[0],f0[1],fill_value="extrapolate",bounds_error=False)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 543, in __init__
    "least %d entries" % minval)
ValueError: x and y arrays must have at least 2 entries
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runwfss.py", line 11, in <module>
    w1.create()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/mirage-0.0.0.dev545+gedcac073-py3.6.egg/mirage/wfss_simulator.py", line 147, in create
    disp_seed.observation(orders=orders)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/NIRCAM_Gsim-1.1-py3.6-linux-x86_64.egg/NIRCAM_Gsim/grism_seed_disperser.py", line 97, in observation
    self.this_one[order].disperse_all()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/NIRCAM_Gsim-1.1-py3.6-linux-x86_64.egg/NIRCAM_Gsim/observations/observations.py", line 199, in disperse_all
    this_object = self.disperse_chunk(i)
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/site-packages/NIRCAM_Gsim-1.1-py3.6-linux-x86_64.egg/NIRCAM_Gsim/observations/observations.py", line 286, in disperse_chunk
    for i,pp in enumerate(all_res, 1):        
  File "/grp/jwst/nis1/kevin/anaconda3/envs/mirage_linux_wfss/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
ValueError: x and y arrays must have at least 2 entries

The code being used is:

#! /usr/bin/env python
#
from mirage import wfss_simulator
import os
import fnmatch
allfiles = os.listdir('./')
goodfiles = fnmatch.filter(allfiles,'f*scene.yaml')
goodfiles.append('jw00042002001_01102_00002_nis_new.yaml')
print(goodfiles)
w1=wfss_simulator.WFSSSim(paramfiles=goodfiles)
w1.create()

I am not sure that this is the way one needs to do it, but I added the w1.create() line so at least it does something after the message about needing to change the yaml files for the grism mode that are part of WFSSSim.__init__ as I see in the code.  The code produces a seed image of dimension 2322x2322 pixels.  Exactly how it does this is not clear to me.  There was no indication that the individual filter images seed images were produced for interpolation in wavelength.

**Comment by NorPirzkal** [comment]
For now, make sure you use at least two different seed images when creating a WFSS simulation. The SED interpolation code in the WFSS module (which is to be replace shortly) requires at least two points in the wavelength,flux input values.
This is a relatively temporary restriction.

N


On Feb 21, 2019, at 6:16 PM, Kevin Volk <notifications@github.com<mailto:notifications@github.com>> wrote:

ValueError: x and y arrays must have at least 2 entries

**Comment by KevinVolkSTScI** [comment]
There are supposed to be six seed images, so something is not being communicated properly in the call.  The list of yaml files has the parameteres for six NIRISS filter images that are supposed to be generated, and then one WFSS yaml file for the grism image.  For whatever reason it is not finding the yaml files properly.

**Comment by bhilbert4** [comment]
@KevinVolkSTScI it looks like the code is again skipping over all the f*scene.yaml files. Are these the same POM mode files you were using the other day? Did you pull down the updates to the branch that allow POM files to be used?

**Comment by KevinVolkSTScI** [comment]
I thought that I was working from the revised branch with the fixes, but it looks like I was not.  When I swtch to the .yaml files with mode = imaging rather than mode = POM the code starts making the imaging scene images.  I have to wait and see whether it produces any spectral images, but it looks like things are working or are close to working this run.

**Comment by KevinVolkSTScI** [comment]
It looks like the first WFSS run that I tried on witserv3 worked properly.  I am running more tests now, and so far things look OK.

**Comment by bhilbert4** [comment]
@KevinVolkSTScI @camipacifici @jotaylor @swara13 Are you all reasonably happy with the WFSS code? I'm looking to merge some of Mirage's long-standing PRs. I'm thinking that as long as these code updates seem to be working well then we can merge, and take care of any smaller issues that pop up in separate PRs.

**Comment by swara13** [comment]
@bhilbert4 I have been doing various tests and NIRISS WFSS simulations are working fine. In my opinion, its okay to merge. Of course, there is more testing to be done, and as issues come up we can deal with that as separate PRs.

**Comment by KevinVolkSTScI** [comment]
I have not done a lot of testing, but it does seem ready to merge to me.

**Comment by camipacifici** [comment]
I have done only a few tests and the very few problems I had were very easily fixed (and you are aware of all of them).
I think it is ok to merge.

-----------------------------------------------------
Dr. Camilla Pacifici
JWST/NIRISS Instrument Scientist
Space Telescope Science Institute
(Muller S307)	

Office phone: 667 218 6543
cpacifici@stsci.edu
camilla.pacifici@gmail.com
-----------------------------------------------------

**Comment by bhilbert4** [comment]
Thanks everyone. I'll merge and we can deal with any bugs we find later. Feel free to create issues if you find any problems.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 I have been looking at the count rates in the WFSS and imaging simulations, and there appears to be a problem.  The total GR150 throughput is about 0.8 with the rest of the light lost due to the anti-reflective coating.  Thus we expect a total count rate in the WFSS seed images lower by 20% than the corresponding imaging values.  What I see is the same count rate in both cases.  It looks like when the source list is assembled the magnitude -> count rate conversion is the same as for direct images.  We should have a grism scaling factor of 0.8 in there when the mode is WFSS.

**Comment by bhilbert4** [comment]
Ok, I can add that in. @NorPirzkal, do we have a similar throughput scaling for NIRCam grisms?

**Comment by KevinVolkSTScI** [comment]
If the grism response values used by Nor's code are already normalized to the throughput of 0.8 then this correction might not be needed.  I was just looking at the source lists to get the count rate values.  I think, though, that the spectra that are produced by Nor's code are rescaled to the input count rate, hence the problem.  In the test case the total signal in the dispersed seed image is much larger than the signal in the direct image, and it looks like the background is too high.  But I am still working on this.  The dispersed seed image has a total signal that is 25 times larger than the direct imaging seed image in the same filter.  This seems rather odd to me.

**Comment by KevinVolkSTScI** [comment]
A note that is unrelated to the previous comment:  I do not see the zero order "spectrum" in the simulations.  Is this as expected?  This is not a problem, I am just curious as to whether it is included in the simulations and I am not seeing it.

**Comment by NorPirzkal** [comment]
The conversion from flam to counts in the WFSS module is done by applying a sensitivity function that converts from erg/s/cm^2/A to e-/s. In the case of NIRCAM, this sensitivity was created by accounting for all of the optics and known transmission and were validated against the ETC estimates.
I am not sure who and how the NIRISS sensitivity function was created so I am not sure what might be going on there but the NIRISS should know and I can help them if they need me to.


On Mar 14, 2019, at 10:42 PM, Kevin Volk <notifications@github.com<mailto:notifications@github.com>> wrote:


If the grism response values used by Nor's code are already normalized to the throughput of 0.8 then this correction might not be needed. I was just looking at the source lists to get the count rate values. I think, though, that the spectra that are produced by Nor's code are rescaled to the input count rate, hence the problem. In the test case the total signal in the dispersed seed image is much larger than the signal in the direct image, and it looks like the background is too high. But I am still working on this. The dispersed seed image has a total signal that is 25 times larger than the direct imaging seed image in the same filter. This seems rather odd to me.

**Comment by KevinVolkSTScI** [comment]
I think that Gabe Brammer created a version of the NIRISS sensitivity function that is being used for Grizli and the same is being used in Nor's code.  I have all the throughputs and can make the conversion values myself, so this should be done to check the current values and make sure that they are using the expected units.  @NorPirzkal can you point me to where the sensitivity files for NIRISS are stored?  I do not expect that there is an error in the sensitivity values, but the background level does not seem to scale properly with the .yaml file inputs so I am guessing that there is a unit problem somewhere in getting from the .yaml file inputs to the inputs for the grism code.

**Comment by KevinVolkSTScI** [comment]
There is clearly some type of issue in scaling from the point source count rates to the dispersed signal count rates.  I ran a model with a single source list where the NIRISS magnitudes are all the same, values 22.5, 20.0, and 17.5 for three sources.  The simulation also specifies zero background.  In the output seed image that is produced from making scene images in the F090W, F115W, F140M, and F150W filters and using the GR150C/F115W combination for the output WFSS simulation, there are two issues:
(1) the background level is about 1.3 ADU/second over the image, where I had specified 0.0 ADU/second background in both the imaging scene image .yaml files and the WFSS .yaml file;
(2) the output signal from the brightest of the three sources was a factor of 13.09 times brighter than the point source image count rates.  It appears that the same factor applies to all three sources.
Looking at the pointsources.list files produced by the imaging simulation in the F115W filter and the grism simulation in the same filter shows that the "target" count rates are the same for both cases.  However a direct measurement of the count rates in the seed image for the WFSS simulation comes out higher than expected.  The input signal for the brightest source is 6444.482 ADU/second in the point source list file, but the signal for the combined spectral orders in the dispersed seed image is 84334 ADU/second after background subtraction.  I would say that the measured signal in the seed image is not good to better than a few percent, but on the seed image for the direct image in the F115W filter the direct photometry on the image matches the input value to about 1% without doing anything fancy.  In any case the discrepancy is quite large between the seed image for the dispersed case and the seed image for direct imaging.

**Comment by NorPirzkal** [comment]
Make sure that Brian incorporated the latest WFSS code. Only the last version rescales the backgrounds to a user input value. All previous ones simply took the NIRCAM WFSS sims I made in e-/s.

On Mar 20, 2019, at 4:51 PM, Kevin Volk <notifications@github.com<mailto:notifications@github.com>> wrote:


There is clearly some type of issue in scaling from the point source count rates to the dispersed signal count rates. I ran a model with a single source list where the NIRISS magnitudes are all the same, values 22.5, 20.0, and 17.5 for three sources. The simulation also specifies zero background. In the output seed image that is produced from making scene images in the F090W, F115W, F140M, and F150W filters and using the GR150C/F115W combination for the output WFSS simulation, there are two issues:
(1) the background level is about 1.3 ADU/second over the image, where I had specified 0.0 ADU/second background in both the imaging scene image .yaml files and the WFSS .yaml file;
(2) the output signal from the brightest of the three sources was a factor of 13.09 times brighter than the point source image count rates. It appears that the same factor applies to all three sources.
Looking at the pointsources.list files produced by the imaging simulation in the F115W filter and the grism simulation in the same filter shows that the "target" count rates are the same for both cases. However a direct measurement of the count rates in the seed image for the WFSS simulation comes out higher than expected. The input signal for the brightest source is 6444.482 ADU/second in the point source list file, but the signal for the combined spectral orders in the dispersed seed image is 84334 ADU/second after background subtraction. I would say that the measured signal in the seed image is not good to better than a few percent, but on the seed image for the direct image in the F115W filter the direct photometry on the image matches the input value to about 1% without doing anything fancy. In any case the discrepancy is quite large between the seed image for the dispersed case and the seed image for direct imaging.

**Pull request merged**
