### PR TITLE
Add a check for colons in some text entries of yaml file

### PR DESCRIPTION
**Pull request by bhilbert4**
Any colons in the Proposal title will cause `yaml.load` to fail.

### CODE REVIEW

**Comment by bhilbert4** [comment]
This work addresses #251.

@KevinVolkSTScI can you either send me the APT file you used when you were having trouble with the yaml files, or else try out this branch yourself on that file? So far, I made changes to `catalog_seed_generator` to look for and remove any colons in the proposal title string when loading the yaml file. I didn't make any changes to the `yaml_generator` yet, since that already appears to have a fix in it that should remove colons prior to writing the yaml file. I don't think that was added anytime recently though. But at least with this fix, any yaml files that do have colons in the title should be handled.

**Comment by KevinVolkSTScI** [comment]
@bhilbert4 -- I will hunt down the APT file again and forward it to you.

**Comment by KevinVolkSTScI** [comment]
I re-ran a test case with a recent version of mirage (installed around February 3) and the APT -> yaml conversion replaces the : in the title string by a , so the conversion runs without crashing.  Thus this problem was fixed sometime between when I tried in early January and when I last re-installed mirage.

**Comment by bhilbert4** [comment]
That's great news. 
I suppose it's still worth keeping the changes I made last night, in case someone creates a yaml file manually and adds a colon to the title name. It seems like a low-probability situation, and the cost is that yaml files are essentially read in twice in the catalog seed generator now. But as you saw, the error message that comes from a yaml file with an extra colon is pretty tough to decipher. Do you agree?

**Comment by KevinVolkSTScI** [comment]
I agree, keep the code in.  There are other kinds of errors one could make manually in a .yaml file that cause the same error (the other one I have managed to do is not leaving a space after the : in the title field when I changed it...) but we cannot guard against everything.  Having a colon in the title or elsewhere is not that usual and people might do that manually.

**Pull request merged**
