### PR TITLE
Add APERNAME value

### PR DESCRIPTION
**Pull request by bhilbert4**
This PR adds code to populate the APERNAME header keyword in the simulation files output by Mirage.  The aperture name has always been used by Mirage. This update just adds that name to the APERNAME keyword. This keyword is not used by the ``jwst`` calibration pipeline, even though it is in the datamodel schema. Folks working on WFSC simulations requested this keyword in order to help with their data analysis.

### CODE REVIEW

**Comment by bhilbert4** [comment]
@Skyhawk172, this is the keyword you needed most, right? Are there any others you need that can be populated with non-dummy information?

**Comment by bhilbert4** [comment]
Resolves #466

**Comment by obi-wan76** [comment]
@bhilbert4 there are a few other things that are missing but not necessarily relevant to WF but it could be useful to add as a way to simulate flight-like information/products. Some of these below with example values. Note that the Aperture Information section also has the keyword PPS_APER (in addition to APERNAME)
 
JWST ephemeris information
REFFRAME= 'EME2000 '           / Ephemeris reference frame                      
EPH_TYPE= 'Predicted'          / Definitive or Predicted                        
EPH_TIME=    58582.71805555555 / UTC time of position and velocity vectors in ep
JWST_X  =    -1360547.19507336 / [km] X spatial coordinate of JWST              
JWST_Y  =    -810427.113333713 / [km] Y spatial coordinate of JWST              
JWST_Z  =    -600441.536402121 / [km] Z spatial coordinate of JWST              
JWST_DX =   0.0241399010725103 / [km/s] X component of JWST velocity            
JWST_DY =  -0.0489741471955144 / [km/s] Y component of JWST velocity            
JWST_DZ =  -0.0883188531102789 / [km/s] Z component of JWST velocity 


Aperture information
APERNAME= 'NRCA3_FULL'         / PRD science aperture used                      
PPS_APER= 'NRCA3_FULL'         / original AperName supplied by PPS              
                                                                      

Velocity aberration correction information
DVA_RA  = 1.73290640112509E-07 / [rad] Velocity aberration correction RA offset 
DVA_DEC = -2.7421264693676E-07 / [rad] Velocity aberration correction Dec offset

Time information                                                                                
BARTDELT=    108.3655483089387 / Barycentric time correction                    
BSTRTIME=    58582.71920444454 / Barycentric exposure start time                
BENDTIME=    58582.71945296388 / Barycentric exposure end time                  
BMIDTIME=    58582.71932870421 / Barycentric exposure mid time                  
HELIDELT=     105.787847796455 / Heliocentric time correction                   
HSTRTIME=    58582.71917461004 / Heliocentric exposure start time               
HENDTIME=    58582.71942312938 / Heliocentric exposure end time                 
HMIDTIME=    58582.71929886971 / Heliocentric exposure mid time  


NIRCam Focus Adjust Mechanism parameters
FAM_LA1 =                    0 / position in steps of linear actuator 1         
FASTEP1 =                    0 / requested focus actuator 1 starting steps      
FAUNIT1 =                  0.0 / requested focus actuator 1 starting units      
FAPHASE1= 'NULL    '           / requested focus actuator 1 starting phase      
FA1VALUE=                    0 / requested focus actuator 1 position value      
FAM_LA2 =                    0 / position in steps of linear actuator 2         
FASTEP2 =                    0 / requested focus actuator 2 starting steps      
FAUNIT2 =                  0.0 / requested focus actuator 2 starting units      
FAPHASE2= 'NULL    '           / requested focus actuator 2 starting phase      
FA2VALUE=                    0 / requested focus actuator 2 position value      
FAM_LA3 =                    0 / position in steps of linear actuator 3         
FASTEP3 =                    0 / requested focus actuator 3 starting steps      
FAUNIT3 =                  0.0 / requested focus actuator 3 starting units      
FAPHASE3= 'NULL    '           / requested focus actuator 3 starting phase      
FA3VALUE=                    0 / requested focus actuator 3 position value   

Guide star information
GS_ORDER=                    1 / index of guide star within list of selected gui
GDSTARID= '0000000000'         / guide star identifier                          
PCS_MODE= 'COARSE  '           / Pointing Control System mode                   
VISITEND= '2019-04-09 19:14:32.4910000' / Observatory UTC time when the visit co

**Comment by Skyhawk172** [comment]
Yes, Bryan, the important one being APERNAME since our analysis tool expects it.

**Comment by bhilbert4** [comment]
Ok, after some trouble with Travis, all the tests are passing. I'm going to merge this now as-is. @obi-wan76 I'm going to open a separate PR for the other keywords you mentioned. Most of those will get dummy values. I'll also need to find a mapping of APERNAME to PPS_APER in order to populate that one.

**Comment by obi-wan76** [comment]
@bhilbert4 Thanks!

**Pull request merged**
