### PR TITLE
NIRISS ami example updates

### PR DESCRIPTION
**Pull request by dthatte**
Updated niriss_ami_example.py so that it works with the latest version of MIRAGE. Updated exposure parameters and used the latest version of APT (27.3.1).

### CODE REVIEW

**Comment by bhilbert4** [comment]
@dthatte let me know if this is ready for review/testing/merging.

**Comment by dthatte** [comment]
@bhilbert4 this is ready for merging.

**Comment by dthatte** [comment]
@bhilbert4 I am wondering if it is a good idea to make .aptx file available in the the input_files folder. Users can then see the file. I see some examples have .aptx file available along with .xml and .pointing files and there are some with only .xml and .pointing.

**Comment by bhilbert4** [comment]
It's up to you if you want to include the apt file or not. Mirage only needs the xml and pointing files to run. You can open the xml file with APT and interact with the proposal, just as with the .aptx file.

**Pull request merged**
