### PR TITLE
Organize directory structure

### PR DESCRIPTION
**Pull request by laurenmarietta**
As described in #129, modifying directory structure to implement a more descriptive sub-package naming scheme.

Now within the `mirage` package there are the following sub-packages: `apt`, `catalogs`, `dark`, `ramp_generator`, `seed_image`, `utils`, and `yaml`.

I updated the import structures within all the scripts and example notebooks (updating for PEP8 compliance along the way).

### CODE REVIEW

**Comment by bhilbert4** [comment]
Looks good! I like having the `imaging_simulator` and `wfss_simulator` at the top level, since those are what most people are going to import. 

Just a couple of suggestions. 

1. Update the version number in setup.py. I've been bad about doing this up until the last couple of PRs. In speaking with the NIRCam team, who are excited to have this go public, they requested a version number that will be tied to the handbook, even if that version number is incremented the next day. It's good practice to keep the version number updated anyway, so I've started trying to do this with each PR.

2. I wonder if the example catalogs that are currently in the `catalogs` directory should be moved over into the `examples` directory?

**Comment by laurenmarietta** [comment]
I am happy to make both of those changes! Is there a place where the version number is being documented? I realized I'm not sure what the current number is...

**Comment by bhilbert4** [comment]
Right now the version number is in `setup.py`. I looked around a little bit a while ago to see how it's most commonly done, but I never found any really great examples other than the number in `setup.py`.

**Comment by laurenmarietta** [comment]
Ah, got it - so would you like me to increment that to 1.1.3 then?

I am in the process of moving the catalog files around and making sure the example notebooks still work - the WFSS notebook is going to take a while, so I will work on that more tomorrow.

**Comment by bhilbert4** [comment]
@Johannes-Sahlmann I was trying at one point last week to figure out how `pysaif` did its versioning. I didn't realize that `relic` was a space telescope package. If setting that up can help with version numbering without us having to update numbers manually each time, then I'm all for it. I read through the example code for the relic package, although it's still not clear to me how it goes about updating the version number. I guess that's a discussion for a different PR though.

And I agree that with the reorganization in this PR, mirage should go to version 2.0.0.

**Pull request merged**
