### PR TITLE
Add NIRISS filter throughputs that include photon yield. 

### PR DESCRIPTION
**Pull request by bhilbert4**
Previous NIRISS filter throughput files did not include the effects of photon yield. This PR replaces those files with throughput curves that do contain photon yield effects. 

The only change to the code is a single line where the suffix of the throughput files to look for has been updated.

My quick test of creating a NIRISS imaging exposure finished successfully.

### CODE REVIEW

**Comment by KevinVolkSTScI** [comment]
When I install the code I see a message

Sorry: TabError: inconsistent use of tabs and spaces in indentation (get_psf.py, line 19)

although it does not seem to cause issues.

**Comment by KevinVolkSTScI** [comment]
The code works OK for full frame image simulation (array_name = NIS_CEN).  However it does not work for any of the subarrays that I tested.  When I set array_name to NIS_AMI4, which worked previously, I get the following error message

>>> t1.create()
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/config/niriss_subarrays.list for Reffiles:subarray_defs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/config/niriss_xtalk_zeros.txt for Reffiles:crossalk input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/config/niriss_zeropoints.list for Reffiles:flux_al input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/config/niriss_readout_pattern.txt for Reffiles:radpattdefs input file
'config' specified: Using /grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/config/placeholder.txt for Reffiles:filter_throuhput input file
Requested readout pattern NISRAPID is valid. Using the nframe = 1 and nskip = 0
Traceback (most recent call last):
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/scripts/catalog_seed_image.py", line 3017, in checkParams
    detector = self.subdict[self.subdict['AperName'] == aper_name]['Detector'][0]
  File "astropy/table/_column_mixins.pyx", line 74, in astropy.table._column_mixins._ColumnGetitemShim.__getitem__
  File "astropy/table/_column_mixins.pyx", line 57, in astropy.table._column_mixins.base_getitem
  File "astropy/table/_column_mixins.pyx", line 69, in astropy.table._column_mixins.column_getitem
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/scripts/imaging_simulator.py", line 56, in create
    cat.make_seed()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/scripts/catalog_seed_image.py", line 108, in make_seed
    self.checkParams()
  File "/grp/jwst/nis1/kevin/anaconda3/envs/pipeline7.1.3/lib/python3.5/site-packages/mirage-1.1-py3.5.egg/mirage/scripts/catalog_seed_image.py", line 3020, in checkParams
    raise ValueError('Unable to determine the detector/module in aperture {}'.format(aper_name))
ValueError: Unable to determine the detector/module in aperture NIS_AMI4

I do not know at what point this error came into the code.  I had run some previous tests using the sub-arrays in early May.  I had not tried re-checking this in the meantime until today.

**Comment by KevinVolkSTScI** [comment]
I am assuming that the throughput files are only used when the jwst_backgrounds code is used.  I have not tested that part of the code explicitly.  The witserv machines were just taken down.  I will check again later.

**Comment by bhilbert4** [comment]
It looks like NIS_AMI4 is not present in the NIRISS subarray list. The full file is below. I would check to see if this agrees with the latest version you gave me, but the power outage means I still don't have access to the server at the moment.

AperName         Name     Detector Filter xstart ystart xend yend num_amps refpix_x refpix_y refpix_v2 refpix_v3
NIS_CEN         FULL        NIS     ANY        0      0 2047 2047    4   1023.5   1023.5      -290.100000  -697.500000
NIS_SOSSTA      SUBTASOSS   NIS     ANY     1922   1166 1985 1229    1   1953.5   1147.5      -351.046558  -686.283309
NIS_AMITA       SUBTAAMI    NIS     ANY     1037     64 1100  127    1   1068.5     95.5      -293.521522  -757.568036
NIS_SUB64       SUB64       NIS     ANY     1984   1984 2047 2047    1   2015.5   2015.5      -355.606946  -632.472638
NIS_SUB80       SUB80       NIS     ANY     1044      0 1123   79    1   1083.5     39.5      0.00      0.00
NIS_SUB128      SUB128      NIS     ANY     1920   1920 2047 2047    1   1983.5   1983.5      -353.493418  -634.567763
NIS_SUB256      SUB256      NIS     ANY     1792   1792 2047 2047    1   1919.5   1919.5      -349.266714  -638.759206
NIS_WFSS64R     WFSS64R     NIS     ANY     1984      0 2047 2047    4   2015.5   1023.5      -354.798256  -712.857164
NIS_WFSS64C     WFSS64C     NIS     ANY        0   1984 2047 2047    1   1023.5   2015.5      -275.805481  -632.103048
NIS_WFSS128R    WFSS128R    NIS     ANY     1920      0 2047 2047    4   1983.5   1023.5      -352.707261  -712.848977
NIS_WFSS128C    WFSS128C    NIS     ANY        0   1920 2047 2047    1   1023.5   1983.5      -275.784605  -634.206813
NIS_SUBSTRIP96  SUBSTRIP96  NIS     ANY        0   1802 2047 1897    1   1023.5   1849.5      -351.046558  -686.283309
NIS_SUBSTRIP256 SUBSTRIP256 NIS     ANY        0   1920 2047 2047    1   1023.5   1983.5      -351.046558  -686.283309
NIS_SUBAMPCAL   SUBAMPCAL   NIS     ANY        0      0  511 1791    1   1023.5   1023.5      -290.100000  -697.500000

**Comment by KevinVolkSTScI** [comment]
The NIS_AMI4 sub-array worked before.  Now NIS_SUB80 is in the subarray list in the config directory but is not on the SIAF .csv file.  So trying NIS_SUB80 in place of NIS_AMI4 does not work either.

**Comment by KevinVolkSTScI** [comment]
Actually I think I remember needing to fix this problem before, adding AMI1 to AMI4 in place of SUB80 so the SIAF file gets the right apertures for SUB80.  I will look into this later today.  I cannot test it until witserv1 to 3 come back up anyway.

**Comment by bhilbert4** [comment]
It looks like the witserv machines are back online now. Machines in the building have been slowly coming back up over the last 30 minutes or so.

**Comment by bhilbert4** [comment]
Sounds good. I'll update the subarray file in the repo and include the fix in this pull request. Assuming that looks ok, maybe it's best to then merge this branch into master, and continue checks on the source positions in subarray data there? Then we can pick up again using issue #91, where the subarray positions were first mentioned.

**Comment by bhilbert4** [comment]
Ok, I've updated the table in the repo. My quick test showed that the simulator did not crash when requesting NIS_AMI1, so I think the new table is all set. I did not look into source locations on the subarray though.

**Comment by KevinVolkSTScI** [comment]
Yes put the change in here since you are updating the other NIRISS files in config anyway.  Getting the stars in the right place in the sub-arrays is rather important so I hope that this can be resolved soon.  I am running a test of the NIS_AMI4 sub-array case now, but it is very slow not being on the witserv1 to witserv3 machines.  To really test things properly I will need to get back on witserv3.

**Comment by bhilbert4** [comment]
As long as the new throughput values and subarray table look ok to you, and your latest test doesn't crash with a `subarray NIS_AMI4 not found` error, could you click `Approve` for your review? Then I'll merge this into the master branch and we can focus on source positions in subarrays.

**Pull request merged**
