### PR TITLE
APT parsing for NIRCam coronagraphy programs (and MIRI coronagraphy, too...)

### PR DESCRIPTION
**Pull request by mperrin**
Addresses #612 to add XML parsing support for NIRCam coronagraphy. 

First steps / work in progress, based on adapting from the NIRISS AMI parsing code (as suggested by @bhilbert4 since that one already deals with TA exposures). Not yet fully working but starting to get there. Needs work on the dither expansion now I think (?).

I'm testing this on my GTO program 1412; 1193 and 1195 are also good test cases.

### CODE REVIEW

**Comment by mperrin** [comment]
@bhilbert4 I got this started but would definitely appreciate any time or guidance you could spare for this. The APT parsing outputs are a little nonintuitive for me  and I'm sort of handwaving my way through adapting this. 

I've gotten as far as being able to run `yam = yaml_generator.SimInput(xml_file, pointing_file)` without error for a NIRCam coronagraphy program, but then the `yam.create_inputs()` stage errors out: 
```
AssertionError: Inconsistent table size from XML file (14) and pointing file (56). 
Something was not processed correctly in apt_inputs.
```

I suspect this is because I'm not expanding the dithers properly yet, or some such. I may poke at this a bit more but I expect you might be able to help steer me in the right direction?   (This isn't immediately urgent, I just wanted to see how far I could get after we talked on Slack yesterday)


FYI @juliengirard @lpueyo

**Comment by bhilbert4** [comment]
No problem. I can have a look at it. Expansion for dithers is done later, after the xml is read in. You need only one entry per exposure setup, if that makes sense. I often see this error when I have forgotten to take into account assumptions that aren't explicitly in the xml file. For example, in the AMI case, there are actually 4 TA exposures, but there's no indication of this in xml. Usually by looking at the entries in the pointing file you can see what is missing.

**Comment by mperrin** [comment]
Also still to do is to sort out the filter + subarray parts of this. This template breaks the mold compared to most of the NIRCam ones because it only returns data from one SCA, and it's sometimes LW and sometimes SW, depending on filter choice.

**Comment by mperrin** [comment]
ooking at this more now and adding some debug print statements I see it's all confused in the parsing of the science exposures, and missing any entries for any of those...

**Comment by mperrin** [comment]
Bonus: now includes APT parsing for MIRI Coronagraphy and MIRI imaging, enough to handle mixed programs containing those along with NIRCam imaging. (Doesn't output YAML for those, naturally, but internally does parse them enough to get the exposure information, enough to correctly interpret .pointing files containing rows for multiple instruments)

Tested on GTO programs 1411, 1412, 1193, 1194. Seems to be working pretty well. 

(Note, should probably test whether any of the small changes I made in the generic template parsing code might cause problems for other templates or other use cases? I would think not, but caution suggests verifying.)

**Comment by mperrin** [comment]
*To Do:*

- [ ] The 'don't write unused detectors' part of the logic for NIRCam Coron should be made smarter for SW exposures, to only use A2 or A4 depending on coron mask, and skip the other 3 A detectors. Right now it's only omitting A5.  For LW coronagraphy it's working right (saving the A5 yaml and omitting all 4 of the SW ones). This needs some updates in yaml_generator.py around line 825. 
- [ ] Test and double check these changes don't have any inadvertent unintended consequences for parsing other templates? 
- [ ] Go over the outputs YAMLs with a fine-toothed comb for correctness of the values. 
- [ ] Test actually running MIRAGE image simulations on these; so far it's only tested through YAML generation.

**Comment by mperrin** [comment]
I just realized this is still open and I had it at draft status. I've moved it to 'ready for review' though I have not done any work on it recently. I think it is indeed ready enough to merge now, and may be useful to do so alongside the other templates work in #637, perhaps.

**Pull request merged**
