### PR TITLE
Made max_frames hard coded value into a kwarg

### PR DESCRIPTION
**Pull request by hover2pi**
Moves hardcoded `max_frames` variable into `SossSim.create` keyword args so users can adjust memory allocation. Addresses #727 .

### CODE REVIEW

**Review by bhilbert4 — APPROVED** [review]
LGTM!

**Comment by bhilbert4** [comment]
#772 has been merged, so you should be able to bring those changes into this branch now. Those missing changes were causing the tests here to fail.

**Comment by hover2pi** [comment]
Hmmm, tests failing here:

```
FAILED tests/test_ra_dec_to_x_y.py::test_gal_rotations[0.0-galaxy_pos_angs0-expected_galaxy_pos_angs0]
FAILED tests/test_ra_dec_to_x_y.py::test_gal_rotations[30.0-galaxy_pos_angs1-expected_galaxy_pos_angs1]
FAILED tests/test_ra_dec_to_x_y.py::test_ext_rotations[30.0-ext_pos_angs1-expected_ext_pos_angs1]
```
I haven't edited these tests or the code in this PR so I must have pulled it in when I merged. Have you seen this error before @bhilbert4 ? Thanks!

**Comment by bhilbert4** [comment]
Weird. Must be related to #767 although the tests were passing there when I merged it. I'll take a look.

**Comment by bhilbert4** [comment]
@hover2pi I checked, and I think all you need to do is pull in the latest upstream/master and the tests here should pass.

**Pull request merged**
